version: "2"
services:
  greetings-db:
    image: greetings-db
    ports:
      - "8080:8080"
    restart: unless-stopped
  greetings-service:
    image: greetings-service
    ports:
      - "8081:8080"
    volumes:
        - $PWD/build/greetings.networking.config:/service/networking.config
    restart: unless-stopped
    depends_on:
      - greetings-db
  gateway:
    image: gateway
    ports:
      - "8082:8080"
    volumes:
        - $PWD/build/gateway.networking.config:/service/networking.config
    restart: unless-stopped
    depends_on:
      - greetings-service
