version: "2"
services:
  db:
    image: greetings-db
    ports:
      - "8080:8080"
    restart: unless-stopped
  greetings:
    image: greetings-service
    ports:
      - "8081:8080"
    volumes:
        - $PWD/build/greetings.networking.config:/service/networking.config
    restart: unless-stopped
    depends_on:
      - db
  gateway:
    image: gateway
    ports:
      - "8082:8080"
    volumes:
        - $PWD/build/gateway.networking.config:/service/networking.config
    restart: unless-stopped
    depends_on:
      - greetings
